### PR TITLE
Specify version bounds on all dependencies

### PR DESCRIPTION
**Pull request by qnoyxu**
This PR puts PVP-compliant version bounds (lower and upper) on all dependencies.

@arowM , please review.

### CODE REVIEW

**Comment by arowM** [comment]
Thank you!
Which version of stackage LTS is this lower/upper boundaries intended for?

**Comment by qnoyxu** [comment]
They are not intending for a specific LTS version.
I didn't explain it enough, but a more concrete explanation of this change is the following:
* To specify upper boundary of each dependencies as maximal version that meets the requirement "any future changes will not cause failing to build our packages".

As long as all packages follows PVP, this requirement will be equivalent to "no destructive changes will be made".
Actually, I didn't change anything about the lower boundaries.

**Comment by arowM** [comment]
OK. I expect this package to support the stackage latest LTS or nightly.
So, hopefully, the version of upper bounds will be a version that supports either.

The good news is that from the CI results, it seems that all of the dependencies in this package support the version included in stack LTS 16.
I'll merge it. Thanks!

**Comment by arowM** [comment]
Could you bump the new version, and upload to hackage?

On another note, would you be interested in sending a PR that reenables tonatona-related packages to the stackage repositories?
The following PR would be helpful.
https://github.com/commercialhaskell/stackage/pull/5699

**Comment by qnoyxu** [comment]
:ok_hand: 
I'll try both!
Thank you so much for sharing the reference URL.

**Pull request merged**
