### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by qunoissue**
This PR includes the following changes:

* Add support for GHC 8.10.7, 9.0.2, 9.2.8 and 9.4.6
  * Version bounds of dependencies are determined as "the minimum range of major versions including those in [LTS 18.10](https://www.stackage.org/lts-18.10) and [LTS-21.8](https://www.stackage.org/lts-21.8)"
* Drop support for GHC < 8.10.7
* Introduce [cabal-doctest](https://github.com/haskellari/cabal-doctest) in order to run doctest via `cabal v2-test`
* Fix GitHub Actions workflows
* Update sample app

### CODE REVIEW

**Comment by arowM** [comment]
Thanks a lot!
I will review your code after you fix the failing tests. 🌷

**Comment by qunoissue** [comment]
Thank you for re-run tests :herb: 
This time it succeeded, so I assumed that "the previous run was affected in some way and will not fail from now on".
Could you please start the review?

**Comment by arowM** [comment]
@qunoissue
Is it your intention to allow Stack CI nightly and Cabal CI latest to not pass their tests?
That's still fine, but in that case, may I ask you to change the configuration file in the .github directory so that those tests are not executed?

I will start a review in parallel with your work.

**Comment by arowM** [comment]
The code itself was not particularly problematic.
I learned a lot about how to write doctest and other things now. 🌷

Once the CI testing is complete, I will merge and release the new version.

**Comment by qunoissue** [comment]
> Is it your intention to allow Stack CI nightly and Cabal CI latest to not pass their tests?

Yes, exactly.
I realized that these tests are unnecessary because they always fail...

> may I ask you to change the configuration file in the .github directory so that those tests are not executed?

I changed it!

**Comment by arowM** [comment]
I've released new versions.
https://hackage.haskell.org/packages/search?terms=tonatona

**Pull request merged**
