### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by qunoissue**
This PR will migrate from Travis CI to Github Actions.
Compared to Travis CI, Github Actions has the advantage of being free and unlimited for co-developers.

I would like to comment on the workflow:
* At this time it does not provide tests using cabal-install.
* Caching on macOS is disabled because it seems to cause failures when installing dependencies. (cf. [article in Japanese](https://debug-ito.hatenablog.com/entry/2021/02/28/121631))

### CODE REVIEW

**Comment by qunoissue** [comment]
The workflow which was executed on the source branch is successful.
https://github.com/qunoissue/tonatona/actions/runs/1955720922

**Comment by arowM** [comment]
Thanks a lot.🌻

I would like to use Travis until I add a test using cabal-install because Hackage tests libraries using cabal-install.
Can you make a revert commit that leaves Travis CI in place, or can you add tests using cabal-install to this PR?

**Comment by qunoissue** [comment]
> Hackage tests libraries using cabal-install

:exploding_head: 
I will add tests using cabal.

I also found some mistakes on the 'stack' side and will fix them.

**Comment by qunoissue** [comment]
Tests by cabal-install were added using automatic generation by [Haskell-CI](https://github.com/haskell-CI/haskell-ci).
GHC versions to be tested are the same as those specified in the existing Travis CI.

Also, some modifications have been made to the tests by Stack.

**Review by arowM — COMMENTED** [review]
Thanks a lot! I can merge, but could you please answer my trivial question beforehand?

What effect the bellow change occurs?

```diff
- , tonatona >=0.1 && <0.2
+ , tonatona ==0.1.*
```

**Comment by qunoissue** [comment]
Unless you use too old Cabal, there is no effect.
According to the [Cabal documentation](https://cabal.readthedocs.io/en/3.6/cabal-package.html#pkg-field-build-depends) the latter is simply syntactic sugar for the former. (since Cabal 1.6)

Since the cabal files are automatically generated by Hpack, this change is probably due to the use of newer version of Hpack.

**Comment by arowM** [comment]
I got it. Thanks!

**Comment by arowM** [comment]
@qunoissue Test failed. 😿
https://github.com/tonatona-project/tonatona/actions/runs/2046998157

**Comment by qunoissue** [comment]
:exploding_head: 
I will fix it.

**Pull request merged**
